name: Lint and tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  cljest-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cljest

    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1224
      - name: Link jest-preset-cljest
        run: npm link ../jest-preset-cljest
      - name: Install dependencies
        run: |
          make install
          cd node_modules/jest-preset-cljest
          npm install
          cd ../..
      - name: Lint
        run: make lint
      - name: Compile and run cljest tests
        run: make jest-ci

  cljest-analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cljest

    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1224
      - name: Analyze with cljdoc-analyzer
        run: make analyze

  jest-preset-cljest-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jest-preset-cljest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Run JS tests
        run: make test-ci
